# Informations du site 
site_name: TNSI_2025-2026
site_description: Numérique et Sciences Informatique en classe de terminal au lycée Notre Dame du Mur de MORLAIX.
site_author: "Eric MADEC" 
copyright: Document partagé par <a href="https://github.com/ericECmorlaix" target="_blank">Eric MADEC</a> &copy; 2025 sous licence <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.fr" target="_blank">CC BY-NC-SA 4.0</a> <br> Illustrations par <a href="https://undraw.co/" target="_blank">UnDraw</a>
site_url: https://ericecmorlaix.github.io/TNSI_2025-2026/

# Dépot du projet 
repo_name: 'TNSI_2025-2026' 
repo_url: https://github.com/ericECmorlaix/TNSI_2025-2026 # Ajoute l'icone et le lien vers le dépot GitHub en haut à droite
edit_uri: edit/main/docs/ # Complément au chemin pour aller depuis `repo_url:` jusqu'au répertoire `docs` ;
# Ce qui permet avec MkDocs-Material d'ajouter un bouton (crayon) d'édition du code source.md d'une page du site depuis le navigateur
# (edit => édition avec connexion | blob, tree => lecture anonyme)

# Structure des dossiers :
docs_dir: docs

# Menu de navigation
nav: 
    - Cahier de texte : index.md  
    - Ressources : ressources.md

    - 1NSI_2023-2024 : https://ericecmorlaix.github.io/1NSI_2023-2024/
    - TSI-NSI_2025-2026 : https://ericecmorlaix.github.io/TSI-NSI_2025-2026/       
       
    

# Définition du thème https://squidfunk.github.io/mkdocs-material/creating-your-site/
theme:
    name: material
    # custom_dir: overrides
    font: false  # RGPD ; pas de fonte Google
    language: fr # français
    logo: images/LogoIO.png 
    favicon: images/LogoIO-deep_purple.png

    palette: # Palettes de couleurs jour/nuit, cf : https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
      - scheme: default # nom du thème clair
        primary: deep purple # couleur primaire des titres, des liens, ..., à prendre dans la liste
        accent: deep orange # couleur d'accentuation au survol des boutons, desliens, ..., à prendre dans la liste
        toggle: # définition du bouton pour switcher de palette
          icon: material/weather-sunny # apparence
          name: Basculer en mode sombre # message
      - scheme: slate # nom du thème sombre
        primary: deep orange
        accent: deep purple
        toggle:
          icon: material/weather-night
          name: Basculer en mode clair

    features:
        - navigation.instant
        - navigation.tabs
        - navigation.expand
        - navigation.top
        - toc.integrate
        - header.autohide


markdown_extensions: # https://squidfunk.github.io/mkdocs-material/reference/abbreviations/
    # extensions de la bibliothèque markdown standard
    - abbr # infobulles sur abbréviations 
    - meta # Métadonnées
    - def_list                      # Les listes de définition.
    - attr_list                     # Un peu de CSS et des attributs HTML.
    - footnotes                     # Notes[^1] de bas de page.  [^1]: ma note.
    - admonition                    # Blocs colorés  !!! info "ma remarque"
    - toc: # Table des matières
        permalink: ⚓︎
        toc_depth: 3
    # extensions de python-markdown https://facelessuser.github.io/pymdown-extensions/
    - pymdownx.details              #   qui peuvent se plier/déplier.
    - pymdownx.caret                # Passage ^^souligné^^ ou en ^exposant^.
    - pymdownx.mark                 # Passage ==surligné==.
    - pymdownx.tilde                # Passage ~~barré~~ ou en ~indice~.
    - pymdownx.highlight            # Coloration syntaxique du code
    - pymdownx.inlinehilite         # pour  `#!python  <python en ligne>`
    - pymdownx.snippets             # Inclusion de fichiers externe.
    - pymdownx.tasklist:            # Cases à cocher  - [ ]  et - [x]
        custom_checkbox:    false   #   avec cases d'origine
        clickable_checkbox: true    #   et cliquables.
    - pymdownx.tabbed:              # Onglets coulissants.  === "Onglet"
        alternate_style: true       # Ajout depuis la version 8
    - pymdownx.superfences          # Imbrication de blocs.
    - pymdownx.keys:                # Touches du clavier.  ++ctrl+d++
        separator: "\uff0b"
    - pymdownx.emoji:               # Émojis  :boom:
        emoji_index:     !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.arithmatex:  # Formules en LaTeX 
        generic: true
    
  

plugins:
  - search # Inclure une barre de recherche
  # - mkdocs-jupyter: # Convertir les fichiers .ipynb et .py en pages du site https://github.com/danielfrg/mkdocs-jupyter
  #     kernel_name: python3
  #     execute: False
  #     include_source: True


extra:
  social: 
    - icon: fontawesome/solid/paper-plane
      link: mailto:eric.madec@ecmorlaix.fr
      name: Pour toute question, suggestion ou commentaire, écrire à l'auteur
    - icon: fontawesome/brands/github
      link: https://github.com/ericECmorlaix/TNSI_2025-2026
      name: dépôt github
    - icon: fontawesome/solid/school
      link: https://www.ecmorlaix.fr/nos-etablissements/lycee-notre-dame-du-mur/
      name: Lycée Notre Dame du Mur


extra_javascript:
  - javascripts/config.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css